#!/bin/bash

# This script is reused from https://github.com/yihui/knitr-examples
# The original author is Yihui Xie

prefix=${1%.*}-
Rscript -e "library(knitr)"\
 -e "opts_knit\$set(base.url='./', progress=FALSE)"\
 -e "opts_chunk\$set(cache.path='cache/$prefix', fig.path='figure/$prefix')"\
 -e "set.seed(123); knit('$1')"

# if there is an extra argument, compile tex to pdf
if [ "$2" != '' ]; then
  texi2pdf -c ${1%.*}.tex
fi
